###

GET http://localhost:3000/

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "sola3l@gmail.com",
    "password": "Aa123456!",
    "accountType":"true"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "sola3l@gmail.com",
    "password": "Aa123456!"
}


###
POST http://localhost:3000/user/edit
Content-Type: application/json

{
    "email": "sola3l@gmail.com",
    "newEmail": "sola4l@gmail.com",
    "newpassword": "Ba123456!",
    "newaccountType":false
}

