###

POST http://localhost:4000/model/getModels
Content-Type: application/json

{
    "id": "668517de495c2e8a1ad6a2a0"
}


###

POST http://199.203.9.196:3000/runImprovement
Content-Type: application/json

{
    "db": "uploads/newData_2024-07-03_11-18-53.csv"
}