###

GET http://localhost:4000/

###
POST http://localhost:4000/user/register
Content-Type: application/json

{
    "fullname":"Solal Ohana",
    "email": "eeeeeeea@gmail.com",
    "password": "Aa123456!",
    "accountType":false
}

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "email": "solalalala@gmail.com",
    "password": "Aa123456!"
}


###
POST http://localhost:4000/user/edit
Content-Type: application/json

{
    "fullname": "solol",
    "email": "solal33333@gmail.com",
    "newEmail": "solalohana@gmail.com",
    "newpassword": "112433Aa!",
    "newaccountType":false
}

###
POST http://localhost:4000/user/delete
Content-Type: application/json

{
    "email": "sola5l@gmail.com"
}

###
POST http://localhost:4000/user/recover-password
Content-Type: application/json

{
    "email": "solalohana@gmail.com"
}

