###

GET http://localhost:3000/

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "elad@gmail.com",
    "password": "Aa123456!",
    "accountType":false
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "sola3l@gmail.com",
    "password": "Aa123456!"
}


###
POST http://localhost:3000/user/edit
Content-Type: application/json

{
    "email": "sola4l@gmail.com",
    "newEmail": "sola5l@gmail.com",
    "newpassword": "Ca123456!",
    "newaccountType":true
}

###
POST http://localhost:3000/user/delete
Content-Type: application/json

{
    "email": "sola5l@gmail.com"
}

